apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-timer

spec:
  replicas: 2
  selector:
    matchLabels:
      app: studio-timer
  template:
    metadata:
      labels:
        app: studio-timer
    spec:
      containers:
      - name: studio-timer
        image: panyu1512/studio-timer:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: studio-timer
spec:
  type: NodePort
  selector:
    app: studio-timer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000